module.exports = {
    FLIGHTS_BODY: "#flt-app > div.gws-flights__flex-column.gws-flights__flex-grow > main.gws-flights__flex-column.gws-flights__active-tab.gws-flights__home-page",
    FLIGHT_SEARCHFORM: "#flt-app > div.gws-flights__flex-column.gws-flights__flex-grow > main.gws-flights__flex-column.gws-flights__active-tab.gws-flights__home-page > div:nth-child(3) > div > div.gws-flights-form__form-card",
    ORIGINALCITY: "#flt-app > div.gws-flights__flex-column.gws-flights__flex-grow > main.gws-flights__flex-column.gws-flights__active-tab.gws-flights__home-page > div:nth-child(3) > div > div.gws-flights-form__form-card > div > div.gws-flights__flex-box.gws-flights__align-center > div.flt-input.gws-flights-form__input-container.gws-flights__flex-box.gws-flights-form__airport-input.gws-flights-form__swapper-right",
    ORIGINALCITY_INPUT: "#sb_ifc50 > input[type=text]",
    ORIGINALCITY_IATACODE: "#flt-app > div.gws-flights__flex-column.gws-flights__flex-grow > main.gws-flights__flex-column.gws-flights__active-tab.gws-flights__home-page > div:nth-child(3) > div > div.gws-flights-form__form-card > div > div.gws-flights__flex-box.gws-flights__align-center > div.flt-input.gws-flights-form__input-container.gws-flights__flex-box.gws-flights-form__airport-input.gws-flights-form__swapper-right > div.gws-flights-form__location-text.gws-flights__flex-filler.gws-flights__ellipsize.gws-flights-form__input-target > span.gws-flights-form__location-list > span > span.gws-flights-form__iata-code",
    DESTINATIONCITY: "#flt-app > div.gws-flights__flex-column.gws-flights__flex-grow > main.gws-flights__flex-column.gws-flights__active-tab.gws-flights__home-page > div:nth-child(3) > div > div.gws-flights-form__form-card > div > div.gws-flights__flex-box.gws-flights__align-center > div.flt-input.gws-flights-form__input-container.gws-flights__flex-box.gws-flights-form__airport-input.gws-flights-form__empty.gws-flights-form__swapper-left",
    DESTINATIONCITY_INPUT: "#sb_ifc50 > input[type=text]",
    DESTINATIONCITY_IATACODE: "#flt-app > div.gws-flights__flex-column.gws-flights__flex-grow > main.gws-flights__flex-column.gws-flights__active-tab.gws-flights__home-page > div:nth-child(3) > div > div.gws-flights-form__form-card > div > div.gws-flights__flex-box.gws-flights__align-center > div.flt-input.gws-flights-form__input-container.gws-flights__flex-box.gws-flights-form__airport-input.gws-flights-form__swapper-left > div.gws-flights-form__location-text.gws-flights__flex-filler.gws-flights__ellipsize.gws-flights-form__input-target > span.gws-flights-form__location-list > span > span.gws-flights-form__iata-code",
    
    //Flight Paths
    FLIGHTPATHBOX: ".gws-flights__white-focus.gws-flights-form__menu-button",
    FLIGHTPATH_MENU: ".mSPnZKpnf91__open",
    FLIGHTPATH_ROUND: "##flt-app > div.gws-flights__flex-column.gws-flights__flex-grow > main.gws-flights__flex-column.gws-flights__active-tab.gws-flights__home-page > div:nth-child(3) > div > div.gws-flights-form__form-card > div > div.gws-flights-form__secondary-constraints.gws-flights__flex-box > div:nth-child(1) > dropdown-menu > div > div.mSPnZKpnf91__menu.mSPnZKpnf91__cover-button.mSPnZKpnf91__open > menu-item.mSPnZKpnf91__menu-item.flt-subhead2.mSPnZKpnf91__selected > span",
    FLIGHTPATH_ONE: "#flt-app > div.gws-flights__flex-column.gws-flights__flex-grow > main.gws-flights__flex-column.gws-flights__active-tab.gws-flights__home-page > div:nth-child(3) > div > div.gws-flights-form__form-card > div > div.gws-flights-form__secondary-constraints.gws-flights__flex-box > div:nth-child(1) > dropdown-menu > div > div.mSPnZKpnf91__menu.mSPnZKpnf91__cover-button.mSPnZKpnf91__open > menu-item:nth-child(2) > span",
    FLIGHTPATH_MULTI: "#flt-app > div.gws-flights__flex-column.gws-flights__flex-grow > main.gws-flights__flex-column.gws-flights__active-tab.gws-flights__home-page > div:nth-child(3) > div > div.gws-flights-form__form-card > div > div.gws-flights-form__secondary-constraints.gws-flights__flex-box > div:nth-child(1) > dropdown-menu > div > div.mSPnZKpnf91__menu.mSPnZKpnf91__cover-button.mSPnZKpnf91__open > menu-item:nth-child(3) > span",

    //Passengers
    PASSENGERBOX: "#flt-pax-button",
    PASSENGERMENU: "#flt-modaldialog",
    PASS_ADULT_INC: "#flt-modaldialog > div > div > div:nth-child(1) > div > div:nth-child(3) > div.gws-flights-widgets-numberpicker__flipper-increment",
    PASS_ADULT_DEC: "#flt-modaldialog > div > div > div:nth-child(1) > div > div:nth-child(1) > div.gws-flights-widgets-numberpicker__flipper-decrement",
    PASS_ADULT_DEC_DISABLED: "#flt-modaldialog > div > div > div:nth-child(1) > div > div.gws-flights-widgets-numberpicker__flipper.gws-flights-widgets-numberpicker__disabled > div.gws-flights-widgets-numberpicker__flipper-decrement",
    PASS_CHILD_INC: "#flt-modaldialog > div > div > div:nth-child(2) > div > div:nth-child(3) > div.gws-flights-widgets-numberpicker__flipper-increment",
    PASS_CHILD_DEC: "#flt-modaldialog > div > div > div:nth-child(2) > div > div:nth-child(1) > div.gws-flights-widgets-numberpicker__flipper-decrement",
    PASS_CHILD_DEC_DISABLED: "#flt-modaldialog > div > div > div:nth-child(2) > div > div.gws-flights-widgets-numberpicker__flipper.gws-flights-widgets-numberpicker__disabled > div.gws-flights-widgets-numberpicker__flipper-decrement",
    PASS_INFANT_INC: "#flt-modaldialog > div > div > div:nth-child(3) > div > div:nth-child(3) > div.gws-flights-widgets-numberpicker__flipper-increment",
    PASS_INFANT_DEC: "#flt-modaldialog > div > div > div:nth-child(3) > div > div:nth-child(1) > div.gws-flights-widgets-numberpicker__flipper-decrement",
    PASS_INFANT_DEC_DISABLED: "#flt-modaldialog > div > div > div:nth-child(3) > div > div.gws-flights-widgets-numberpicker__flipper.gws-flights-widgets-numberpicker__disabled > div.gws-flights-widgets-numberpicker__flipper-decrement",
    PASS_INFANTLAP_INC: "#flt-modaldialog > div > div > div:nth-child(4) > div > div:nth-child(3) > div.gws-flights-widgets-numberpicker__flipper-increment",
    PASS_INFANTLAP_DEC: "#flt-modaldialog > div > div > div:nth-child(4) > div > div:nth-child(1) > div.gws-flights-widgets-numberpicker__flipper-decrement",
    PASS_INFANTLAP_DEC_DISABLED: "#flt-modaldialog > div > div > div:nth-child(4) > div > div.gws-flights-widgets-numberpicker__flipper.gws-flights-widgets-numberpicker__disabled > div.gws-flights-widgets-numberpicker__flipper-decrement",
    PASSENGER_CANCEL: "#flt-modaldialog > div > div > div.gws-flights__dialog-button-container.oMol8b > div:nth-child(2)",
    PASSENGER_DONE: "#flt-modaldialog > div > div > div.gws-flights__dialog-button-container.oMol8b > div.gws-flights__dialog-button.gws-flights__dialog-primary-button",

    //Seating
    SEATINGBOX: "#flt-app > div.gws-flights__flex-column.gws-flights__flex-grow > main.gws-flights__flex-column.gws-flights__active-tab.gws-flights__home-page > div:nth-child(3) > div > div.gws-flights-form__form-card > div > div.gws-flights-form__secondary-constraints.gws-flights__flex-box > div.gws-flights__seating_class_dropdown > div",
    SEATINGMENU: "#flt-app > div.gws-flights__flex-column.gws-flights__flex-grow > main.gws-flights__flex-column.gws-flights__active-tab.gws-flights__home-page > div:nth-child(3) > div > div.gws-flights-form__form-card > div > div.gws-flights-form__secondary-constraints.gws-flights__flex-box > div.gws-flights__seating_class_dropdown > div > div.z6mTee.Zzj1ye.cKItof",
    SEAT_ECONOMY: "#flt-app > div.gws-flights__flex-column.gws-flights__flex-grow > main.gws-flights__flex-column.gws-flights__active-tab.gws-flights__home-page > div:nth-child(3) > div > div.gws-flights-form__form-card > div > div.gws-flights-form__secondary-constraints.gws-flights__flex-box > div.gws-flights__seating_class_dropdown > div > div.z6mTee.Zzj1ye.cKItof > div > menu-item:nth-child(1) > span",
    SEAT_PREM_ECONOMY: "#flt-app > div.gws-flights__flex-column.gws-flights__flex-grow > main.gws-flights__flex-column.gws-flights__active-tab.gws-flights__home-page > div:nth-child(3) > div > div.gws-flights-form__form-card > div > div.gws-flights-form__secondary-constraints.gws-flights__flex-box > div.gws-flights__seating_class_dropdown > div > div.z6mTee.Zzj1ye.cKItof > div > menu-item:nth-child(2) > span",
    SEAT_BUSINESS: "#flt-app > div.gws-flights__flex-column.gws-flights__flex-grow > main.gws-flights__flex-column.gws-flights__active-tab.gws-flights__home-page > div:nth-child(3) > div > div.gws-flights-form__form-card > div > div.gws-flights-form__secondary-constraints.gws-flights__flex-box > div.gws-flights__seating_class_dropdown > div > div.z6mTee.Zzj1ye.cKItof > div > menu-item:nth-child(3) > span",
    SEAT_FIRSTCLASS: "#flt-app > div.gws-flights__flex-column.gws-flights__flex-grow > main.gws-flights__flex-column.gws-flights__active-tab.gws-flights__home-page > div:nth-child(3) > div > div.gws-flights-form__form-card > div > div.gws-flights-form__secondary-constraints.gws-flights__flex-box > div.gws-flights__seating_class_dropdown > div > div.z6mTee.Zzj1ye.cKItof > div > menu-item:nth-child(4) > span",

    //Calender
    CALENDER_DIALOG: ".gws-flights__modal-dialog",
    CALENDER_DEPARTDATE: "#flt-app > div.gws-flights__flex-column.gws-flights__flex-grow > main.gws-flights__flex-column.gws-flights__active-tab.gws-flights__home-page > div:nth-child(3) > div > div.gws-flights-form__form-card > div > div.gws-flights__flex-box.gws-flights__align-center > div.gws-flights-form__input-container.gws-flights__flex-box.gws-flights__flex-filler.gws-flights-form__calendar-input.flt-body2 > div.flt-input.gws-flights__flex-box.gws-flights__flex-filler.gws-flights-form__departure-input.gws-flights-form__round-trip > div.gws-flights__flex-filler.gws-flights__ellipsize.gws-flights-form__input-target",
    CALENDER_RETURNDATE: "#flt-app > div.gws-flights__flex-column.gws-flights__flex-grow > main.gws-flights__flex-column.gws-flights__active-tab.gws-flights__home-page > div:nth-child(3) > div > div.gws-flights-form__form-card > div > div.gws-flights__flex-box.gws-flights__align-center > div.gws-flights-form__input-container.gws-flights__flex-box.gws-flights__flex-filler.gws-flights-form__calendar-input.flt-body2 > div.flt-input.gws-flights__flex-box.gws-flights__flex-filler.gws-flights-form__return-input > div.gws-flights__flex-filler.gws-flights__ellipsize.gws-flights-form__input-target",
    CALENDER_DEPARTDATE_ONEWAY: "#flt-app > div.gws-flights__flex-column.gws-flights__flex-grow > main.gws-flights__flex-column.gws-flights__active-tab.gws-flights__home-page > div:nth-child(3) > div > div.gws-flights-form__form-card > div > div.gws-flights__flex-box.gws-flights__align-center > div.gws-flights-form__input-container.gws-flights__flex-box.gws-flights__flex-filler.gws-flights-form__calendar-input.flt-body2 > div.flt-input.gws-flights__flex-box.gws-flights__flex-filler.gws-flights-form__departure-input > div.gws-flights__flex-filler.gws-flights__ellipsize.gws-flights-form__input-target",
    CALENDER_DEPARTDATE_INPUT: "#flt-modaldialog > div > div.xshS2d.gws-flights__flex-box > div.s8NXHf.gws-flights__flex-filler.gws-flights__flex-box > div.tj3PF.gws-flights__flex-filler.gws-flights__flex-box.i88iIb > date-input > input",
    CALENDER_RETURNDATE_INPUT: "#flt-modaldialog > div > div.xshS2d.gws-flights__flex-box > div.s8NXHf.gws-flights__flex-filler.gws-flights__flex-box > div:nth-child(3)",
    CALENDER_DEPARTDATE_ONEWAY_INPUT: "#flt-modaldialog > div > div.xshS2d.gws-flights__flex-box > div.s8NXHf.gws-flights__flex-filler.gws-flights__flex-box > div.tj3PF.gws-flights__flex-filler.gws-flights__flex-box.i88iIb > date-input > input",
    CALENDER_DONE: "#flt-modaldialog > div > div.aFxfpc > g-raised-button > div",

    //Results
    RESULTS_BODY: "#flt-app > div.gws-flights__flex-column.gws-flights__flex-grow > main.gws-flights__flex-column.gws-flights__active-tab.gws-flights__flights-search > div.gws-flights__flex-grow.gws-flights-results__results.gws-flights__flex-column.gws-flights__scrollbar-padding",
    RESULTS_BEST: "#flt-app > div.gws-flights__flex-column.gws-flights__flex-grow > main.gws-flights__flex-column.gws-flights__active-tab.gws-flights__flights-search > div.gws-flights__flex-grow.gws-flights-results__results.gws-flights__flex-column.gws-flights__scrollbar-padding > div.gws-flights-results__results-container.gws-flights__center-content > div.gws-flights__flex-grow.gws-flights-results__slice-results-desktop > div.gws-flights-results__best-flights > ol > li",
    RESULTS_BESTRETURN: "#flt-app > div.gws-flights__flex-column.gws-flights__flex-grow > main.gws-flights__flex-column.gws-flights__active-tab.gws-flights__flights-search > div.gws-flights__flex-grow.gws-flights-results__results.gws-flights__flex-column.gws-flights__scrollbar-padding > div.gws-flights-results__results-container.gws-flights__center-content > div.gws-flights__flex-grow.gws-flights-results__slice-results-desktop > div.gws-flights-results__best-flights > ol > li:nth-child(1) > div",
    RESULTS_BEST_ROUTE: "#flt-app > div.gws-flights__flex-column.gws-flights__flex-grow > main.gws-flights__flex-column.gws-flights__active-tab.gws-flights__flights-search > div.gws-flights__flex-grow.gws-flights-results__results.gws-flights__flex-column.gws-flights__scrollbar-padding > div.gws-flights-results__results-container.gws-flights__center-content > div.gws-flights__flex-grow.gws-flights-results__slice-results-desktop > div.gws-flights-results__best-flights > ol > li > div > div.gws-flights-widgets-expandablecard__header.gws-flights-results__itinerary-card-header > div.gws-flights-results__itinerary-card-summary.gws-flights-results__result-item-summary.gws-flights__flex-box > div.gws-flights-results__select-header.gws-flights__flex-filler > div.gws-flights-results__collapsed-itinerary.gws-flights-results__itinerary",
    RESULTS_BESTRETURN_ROUTE: "#flt-app > div.gws-flights__flex-column.gws-flights__flex-grow > main.gws-flights__flex-column.gws-flights__active-tab.gws-flights__flights-search > div.gws-flights__flex-grow.gws-flights-results__results.gws-flights__flex-column.gws-flights__scrollbar-padding > div.gws-flights-results__results-container.gws-flights__center-content > div.gws-flights__flex-grow.gws-flights-results__slice-results-desktop > div.gws-flights-results__best-flights > ol > li:nth-child(1) > div > div.gws-flights-widgets-expandablecard__header.gws-flights-results__itinerary-card-header > div.gws-flights-results__itinerary-card-summary.gws-flights-results__result-item-summary.gws-flights__flex-box > div.gws-flights-results__select-header.gws-flights__flex-filler > div.gws-flights-results__collapsed-itinerary.gws-flights-results__itinerary",
    RESULTS_OTHER: "#flt-app > div.gws-flights__flex-column.gws-flights__flex-grow > main.gws-flights__flex-column.gws-flights__active-tab.gws-flights__flights-search > div.gws-flights__flex-grow.gws-flights-results__results.gws-flights__flex-column.gws-flights__scrollbar-padding > div.gws-flights-results__results-container.gws-flights__center-content > div.gws-flights__flex-grow.gws-flights-results__slice-results-desktop > div:nth-child(3) > div:nth-child(1) > ol",
    RESULTS_DISPLAY_MORE: "#flt-app > div.gws-flights__flex-column.gws-flights__flex-grow > main.gws-flights__flex-column.gws-flights__active-tab.gws-flights__flights-search > div.gws-flights__flex-grow.gws-flights-results__results.gws-flights__flex-column.gws-flights__scrollbar-padding > div.gws-flights-results__results-container.gws-flights__center-content > div.gws-flights__flex-grow.gws-flights-results__slice-results-desktop > div:nth-child(3) > div:nth-child(1) > div.gws-flights-results__dominated-toggle.flt-subhead2.gws-flights-results__collapsed",
    RESULTS_DISPLAYRETURN_MORE: "#flt-app > div.gws-flights__flex-column.gws-flights__flex-grow > main.gws-flights__flex-column.gws-flights__active-tab.gws-flights__flights-search > div.gws-flights__flex-grow.gws-flights-results__results.gws-flights__flex-column.gws-flights__scrollbar-padding > div.gws-flights-results__results-container.gws-flights__center-content > div.gws-flights__flex-grow.gws-flights-results__slice-results-desktop > div:nth-child(3) > div:nth-child(1) > div.gws-flights-results__dominated-toggle.flt-subhead2.gws-flights-results__collapsed",
    RESULTS_HIDE_MORE: "#flt-app > div.gws-flights__flex-column.gws-flights__flex-grow > main.gws-flights__flex-column.gws-flights__active-tab.gws-flights__flights-search > div.gws-flights__flex-grow.gws-flights-results__results.gws-flights__flex-column.gws-flights__scrollbar-padding > div.gws-flights-results__results-container.gws-flights__center-content > div.gws-flights__flex-grow.gws-flights-results__slice-results-desktop > div:nth-child(3) > div:nth-child(1) > div.gws-flights-results__dominated-toggle.flt-subhead2.gws-flights-results__expanded",
    RESULTS_FLIGHTS: ".gws-flights-results__result-item.gws-flights__flex-box.gws-flights-results__collapsed",

}